// Generated by CoffeeScript 1.6.3
var Solution;

Solution = (function() {
  function Solution(gen) {
    this.gen = gen != null ? gen : 0;
    return;
  }

  return Solution;

})();

exports.Solution = Solution;
